version: '3.8'

services:
  web:
    build: ./app
    container_name: vpm-repo-web
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "2828:3000"
    environment:
      - DATA_DIR=/data
    networks:
      - vpm_network



networks:
  vpm_network:
    driver: bridge
